name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build ISO file
      run: make
    - name: Upload ISO file to Actions tab
      uses: actions/upload-artifact@v3
      with:          
        name: archlinux-iso
        path: ./iso/archlinux-*.iso
